import { INodeProperties } from 'n8n-workflow';

const instanceOperations = [
	'events',
	'messages',
	'contacts',
	'chats',
	'groups',
	'media',
	'message-revisions',
	'receipts',
	'reactions',
	'memberships',
	'calls',
	'sync-gaps',
	'backfill',
	'preview-purge',
	'tombstones',
	'verify',
];
const searchOperations = [
	'events',
	'messages',
	'contacts',
	'chats',
	'groups',
	'media',
	'receipts',
	'reactions',
	'memberships',
	'calls',
	'sync-gaps',
];

export const archiveFields: INodeProperties[] = [
	{
		displayName: 'Instance Name',
		name: 'archiveInstanceName',
		type: 'string',
		required: true,
		default: '',
		displayOptions: { show: { resource: ['archive-api'], operation: instanceOperations } },
		description: 'Evolution instance whose durable archive should be accessed',
	},
	{
		displayName: 'Query',
		name: 'archiveQuery',
		type: 'json',
		default: '{}',
		displayOptions: { show: { resource: ['archive-api'], operation: searchOperations } },
		description:
			'JSON query parameters. Supported fields include entityJid, groupJid, eventType, entityType, from, before, mediaType, state, and limit.',
	},
	{
		displayName: 'Include Decrypted Payload',
		name: 'archiveIncludePayload',
		type: 'boolean',
		default: false,
		displayOptions: { show: { resource: ['archive-api'], operation: ['events'] } },
		description: 'Whether to return the exact captured event data; requires archive:export',
	},
	{
		displayName: 'Policy ID',
		name: 'archivePolicyId',
		type: 'string',
		default: '',
		displayOptions: { show: { resource: ['archive-api'], operation: ['put-policy'] } },
		description:
			'Leave empty to create a policy; provide an existing ID to create its next version',
	},
	{
		displayName: 'Message ID',
		name: 'archiveMessageId',
		type: 'string',
		required: true,
		default: '',
		displayOptions: { show: { resource: ['archive-api'], operation: ['message-revisions'] } },
		description: 'WhatsApp message ID whose complete observed revision history should be returned',
	},
	{
		displayName: 'Chat JID',
		name: 'archiveMessageChatJid',
		type: 'string',
		default: '',
		displayOptions: { show: { resource: ['archive-api'], operation: ['message-revisions'] } },
		description: 'Optional chat JID used to disambiguate the message ID',
	},
	{
		displayName: 'Policy Scope',
		name: 'archivePolicyScope',
		type: 'options',
		default: 'general',
		displayOptions: { show: { resource: ['archive-api'], operation: ['put-policy'] } },
		options: [
			{ name: 'General', value: 'general' },
			{ name: 'Entity Type', value: 'entity' },
			{ name: 'Account', value: 'account' },
			{ name: 'Specific JID', value: 'jid' },
		],
	},
	{
		displayName: 'Selector',
		name: 'archivePolicySelector',
		type: 'json',
		default: '{}',
		displayOptions: { show: { resource: ['archive-api'], operation: ['put-policy'] } },
		description:
			'For example {"entityType":"group"} or {"instanceName":"support","jid":"120363...@g.us"}',
	},
	{
		displayName: 'Policy',
		name: 'archivePolicy',
		type: 'json',
		required: true,
		default:
			'{"capture":{"events":true,"messages":true},"media":{"mode":"all"},"retentionDays":null}',
		displayOptions: { show: { resource: ['archive-api'], operation: ['put-policy'] } },
		description: 'Prospective capture, media, direction, retention, and recovery settings',
	},
	{
		displayName: 'Row Limit',
		name: 'archiveBackfillLimit',
		type: 'number',
		default: 10000,
		typeOptions: { minValue: 1, maxValue: 100000 },
		displayOptions: { show: { resource: ['archive-api'], operation: ['backfill'] } },
		description: 'Maximum rows from each operational entity type to import',
	},
	{
		displayName: 'Purge Criteria',
		name: 'archivePurgeCriteria',
		type: 'json',
		required: true,
		default: '{"before":"2026-01-01T00:00:00Z"}',
		displayOptions: { show: { resource: ['archive-api'], operation: ['preview-purge'] } },
		description:
			'At least one of before, entityJid, groupJid, or eventTypes is required. Set mediaOnly to retain events.',
	},
	{
		displayName: 'Preview ID',
		name: 'archivePreviewId',
		type: 'string',
		required: true,
		default: '',
		displayOptions: { show: { resource: ['archive-api'], operation: ['confirm-purge'] } },
	},
	{
		displayName: 'Confirmation Token',
		name: 'archiveConfirmationToken',
		type: 'string',
		typeOptions: { password: true },
		required: true,
		default: '',
		displayOptions: { show: { resource: ['archive-api'], operation: ['confirm-purge'] } },
		description: 'One-time token returned by Preview Purge',
	},
];
