import { INodeProperties } from 'n8n-workflow';

export const baileysMethodNames = [
	'communityMetadata',
	'communityCreate',
	'communityCreateGroup',
	'communityLeave',
	'communityUpdateSubject',
	'communityLinkGroup',
	'communityUnlinkGroup',
	'communityFetchLinkedGroups',
	'communityRequestParticipantsList',
	'communityRequestParticipantsUpdate',
	'communityParticipantsUpdate',
	'communityUpdateDescription',
	'communityInviteCode',
	'communityRevokeInvite',
	'communityAcceptInvite',
	'communityRevokeInviteV4',
	'communityAcceptInviteV4',
	'communityGetInviteInfo',
	'communityToggleEphemeral',
	'communitySettingUpdate',
	'communityMemberAddMode',
	'communityJoinApprovalMode',
	'communityFetchAllParticipating',
	'getOrderDetails',
	'getCatalog',
	'getCollections',
	'productCreate',
	'productDelete',
	'productUpdate',
	'updateBussinesProfile',
	'updateCoverPhoto',
	'removeCoverPhoto',
	'sendMessageAck',
	'sendRetryRequest',
	'rejectCall',
	'fetchMessageHistory',
	'requestPlaceholderResend',
	'issuePrivacyTokens',
	'relayMessage',
	'sendReceipt',
	'sendReceipts',
	'readMessages',
	'refreshMediaConn',
	'getMediaHost',
	'waUploadToServer',
	'fetchPrivacySettings',
	'sendPeerDataOperationMessage',
	'updateMemberLabel',
	'updateMediaMessage',
	'sendMessage',
	'newsletterCreate',
	'newsletterUpdate',
	'newsletterSubscribers',
	'newsletterMetadata',
	'newsletterFollow',
	'newsletterUnfollow',
	'newsletterMute',
	'newsletterUnmute',
	'newsletterUpdateName',
	'newsletterUpdateDescription',
	'newsletterUpdatePicture',
	'newsletterRemovePicture',
	'newsletterReactMessage',
	'newsletterFetchMessages',
	'subscribeNewsletterUpdates',
	'newsletterAdminCount',
	'newsletterChangeOwner',
	'newsletterDemote',
	'newsletterDelete',
	'groupMetadata',
	'groupCreate',
	'groupLeave',
	'groupUpdateSubject',
	'groupRequestParticipantsList',
	'groupRequestParticipantsUpdate',
	'groupParticipantsUpdate',
	'groupUpdateDescription',
	'groupInviteCode',
	'groupRevokeInvite',
	'groupAcceptInvite',
	'groupRevokeInviteV4',
	'groupAcceptInviteV4',
	'groupGetInviteInfo',
	'groupToggleEphemeral',
	'groupSettingUpdate',
	'groupMemberAddMode',
	'groupJoinApprovalMode',
	'groupFetchAllParticipating',
	'createCallLink',
	'getBotListV2',
	'sendPresenceUpdate',
	'presenceSubscribe',
	'fetchBlocklist',
	'fetchStatus',
	'fetchDisappearingDuration',
	'updateProfilePicture',
	'removeProfilePicture',
	'updateProfileStatus',
	'updateProfileName',
	'updateBlockStatus',
	'updateDisableLinkPreviewsPrivacy',
	'updateCallPrivacy',
	'updateMessagesPrivacy',
	'updateLastSeenPrivacy',
	'updateOnlinePrivacy',
	'updateProfilePicturePrivacy',
	'updateStatusPrivacy',
	'updateReadReceiptsPrivacy',
	'updateGroupsAddPrivacy',
	'updateDefaultDisappearingMode',
	'getBusinessProfile',
	'resyncAppState',
	'chatModify',
	'cleanDirtyBits',
	'addOrEditContact',
	'removeContact',
	'addLabel',
	'addChatLabel',
	'removeChatLabel',
	'addMessageLabel',
	'removeMessageLabel',
	'star',
	'addOrEditQuickReply',
	'removeQuickReply',
	'fetchAccountReachoutTimelock',
	'fetchNewChatMessageCap',
	'appPatch',
	'query',
	'sendRawMessage',
	'uploadPreKeys',
	'uploadPreKeysToServerIfRequired',
	'digestKeyBundle',
	'rotateSignedPreKey',
	'requestPairingCode',
	'sendUnifiedSession',
	'sendWAMBuffer',
] as const;

export const baileysOperations: INodeProperties = {
	displayName: 'Operation',
	name: 'operation',
	type: 'options',
	noDataExpression: true,
	displayOptions: {
		show: {
			resource: ['baileys-api'],
		},
	},
	options: baileysMethodNames.map((method) => ({
		name: method,
		value: method,
		action: `Invoke ${method}`,
		description: `Invoke Baileys WASocket.${method} with ordered JSON arguments`,
	})),
	default: 'sendMessage',
};
